package tw.market.ledger.feature.alert
import androidx.compose.ui.test.*;import androidx.compose.ui.test.junit4.createComposeRule;import kotlinx.coroutines.Dispatchers;import kotlinx.coroutines.ExperimentalCoroutinesApi;import kotlinx.coroutines.test.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.RobolectricTestRunner;import org.robolectric.annotation.Config;import tw.market.ledger.feature.alert.domain.AlertRepository;import tw.market.ledger.feature.alert.presentation.*;import tw.market.ledger.model.*;import tw.market.ledger.network.AlertRuleInput
import tw.market.ledger.feature.alert.domain.LocalNotificationDelivery
private val rule=AlertRule("r","MA20突破",AlertType.MA_CROSS_ABOVE,AlertScope.SECURITY,true,20)
private val event=AlertEvent("e","1234","測試股票","2026-08-11T10:00:00Z","2026-08-11","MA_CROSS_ABOVE","11","10","MA20","1234 收盤由 MA20 下方突破至上方","FINAL",null)
private class Repo(var data:AlertDashboard=AlertDashboard(listOf(rule),listOf(event))):AlertRepository{val calls=mutableListOf<String>();override suspend fun dashboard()=data;override suspend fun create(input:AlertRuleInput){calls+="create"};override suspend fun edit(id:String,input:AlertRuleInput){calls+="edit"};override suspend fun delete(id:String){calls+="delete"};override suspend fun toggle(id:String,enabled:Boolean){calls+="toggle"};override suspend fun read(id:String){calls+="read"};override suspend fun readAll(){calls+="all"}}
@OptIn(ExperimentalCoroutinesApi::class) class AlertViewModelTest{private val dispatcher=StandardTestDispatcher();@Before fun before()=Dispatchers.setMain(dispatcher);@After fun after()=Dispatchers.resetMain();@Test fun mutationsAndOffline(){runTest(dispatcher){val repo=Repo();val vm=AlertViewModel(repo);dispatcher.scheduler.advanceUntilIdle();vm.toggle("r",false);vm.delete("r");vm.read("e");vm.readAll();dispatcher.scheduler.advanceUntilIdle();Assert.assertEquals(listOf("toggle","delete","read","all"),repo.calls);repo.data=repo.data.copy(offline=true);vm.refresh();dispatcher.scheduler.advanceUntilIdle();assert(vm.state.value is AlertUiState.Offline)}}}

@RunWith(RobolectricTestRunner::class) @Config(sdk=[35]) class RealtimeAlertComposeTest{
 @get:Rule val compose=createComposeRule()
 @Test fun modeProviderBannerAndRealtimeBadge(){compose.setContent{CreateAlertScreen(realtimeProviderStatus="UNCONFIGURED")};compose.onNodeWithTag("alert-evaluation-mode").assertIsDisplayed();compose.onNodeWithText("盤中即時").performClick();compose.onNodeWithTag("realtime-provider-unavailable").assertIsDisplayed()}
 @Test fun realtimeEventBadge(){val realtime=event.copy(evaluationMode=AlertEvaluationMode.REALTIME);compose.setContent{NotificationCenterScreen(AlertUiState.Success(AlertDashboard(emptyList(),listOf(realtime))))};compose.onNodeWithText("未讀 · 盤中 · 1234 測試股票").assertIsDisplayed()}
 @Test fun localNotificationDeduplicatesFingerprint(){val delivery=LocalNotificationDelivery();val realtime=event.copy(fingerprint="same");Assert.assertTrue(delivery.shouldDeliver(realtime));Assert.assertFalse(delivery.shouldDeliver(realtime))}
}
